name: flutter-folio
version: 1.1.4
summary: A scrapbooking app that feels great on all your devices
description: Make your digital scrapbooks with Flutter Folio! You can upload photos from your phone, edit them on a desktop or tablet and share them with friends and family on the web.

confinement: strict
base: core18
grade: stable

apps:
  flutter-folio:
    command: flutter_folio
    extensions: [flutter-dev]
    plugs:
    - network
    - home

parts:
  flutter-folio:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

